/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#1e211f",
        "on-primary-fixed-variant": "#254a65",
        "on-secondary-container": "#cceace",
        "primary-fixed": "#cbe6ff",
        "node-border": "#313633",
        "canvas-bg": "#121412",
        "sage-muted": "#6b8a6d",
        "warm-sand": "#3d3834",
        "on-primary-container": "#fcfcff",
        "inverse-on-surface": "#eff1f1",
        "on-background": "#e1e3e0",
        "surface-bright": "#1a1c1a",
        "tertiary-container": "#4d3d2e",
        "secondary-fixed": "#cceace",
        "on-primary-fixed": "#001e30",
        "on-tertiary-container": "#ffdcbd",
        "error": "#ffb4ab",
        "tertiary-fixed": "#ffdcbd",
        "on-surface": "#e1e3e0",
        "on-secondary-fixed-variant": "#334d38",
        "on-tertiary": "#4a2800",
        "primary-fixed-dim": "#a7cbeb",
        "on-tertiary-fixed-variant": "#ffdcbd",
        "primary-container": "#3f627e",
        "surface": "#121412",
        "surface-container-lowest": "#0a0c0a",
        "error-container": "#93000a",
        "primary": "#a7cbeb",
        "surface-container-highest": "#313633",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#272b28",
        "secondary-container": "#334d38",
        "surface-tint": "#a7cbeb",
        "inverse-primary": "#3c5f7b",
        "on-primary": "#00344d",
        "secondary": "#b0ceb2",
        "inverse-surface": "#e1e3e0",
        "tertiary": "#f7bb7e",
        "on-surface-variant": "#c2c9c2",
        "on-tertiary-fixed": "#2c1600",
        "secondary-fixed-dim": "#b0ceb2",
        "outline-variant": "#424942",
        "outline": "#8b938b",
        "blue-slate": "#8db0cc",
        "on-secondary": "#1d3522",
        "on-error": "#690005",
        "surface-dim": "#121412",
        "background": "#121412",
        "on-secondary-fixed": "#07200f",
        "surface-variant": "#424942",
        "tertiary-fixed-dim": "#f7bb7e",
        "surface-container-low": "#1a1c1a",
        
        // Light Theme overrides / complements
        "light-bg": "#faf6f0",
        "light-surface": "#ffffff",
        "light-node-border": "#E1E8ED",
        "light-primary": "#3c5f7b",
        "light-secondary": "#4a654e",
        "light-tertiary": "#7f521f"
      },
      borderRadius: {
        "DEFAULT": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "max-content-width": "1440px",
        "sidebar-width": "320px",
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["Inter", "monospace"]
      }
    },
  },
  plugins: [],
}
