/**
 * SoulCare — Tailwind design tokens
 * Green is accent/action only; cream & warm neutrals dominate.
 */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './pages/**/*.{js,ts,jsx,tsx}',
    './app/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fcf9f8',
        surface: '#f0eded',
        'surface-dim': '#dcd9d9',
        'surface-bright': '#fcf9f8',
        'surface-lowest': '#ffffff',
        'surface-low': '#f6f3f2',
        'surface-high': '#eae7e7',
        'surface-highest': '#e4e2e1',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3f2',
        'surface-container': '#f0eded',
        'surface-container-high': '#eae7e7',
        'surface-container-highest': '#e4e2e1',
        'surface-variant': '#e4e2e1',
        'surface-tint': '#486552',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#424843',
        'inverse-surface': '#303030',
        'inverse-on-surface': '#f3f0f0',
        primary: '#45614e',
        'on-primary': '#ffffff',
        'primary-container': '#5d7a66',
        'on-primary-container': '#eefff0',
        'inverse-primary': '#afceb7',
        'primary-fixed': '#caead2',
        'primary-fixed-dim': '#afceb7',
        'on-primary-fixed': '#052012',
        'on-primary-fixed-variant': '#314d3b',
        secondary: '#625e55',
        'on-secondary': '#ffffff',
        'secondary-container': '#e8e2d6',
        'on-secondary-container': '#68645b',
        'secondary-fixed': '#e8e2d6',
        'secondary-fixed-dim': '#cbc6ba',
        'on-secondary-fixed': '#1e1c14',
        'on-secondary-fixed-variant': '#4a473e',
        tertiary: '#4e5f49',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#667860',
        'on-tertiary-container': '#efffe5',
        'tertiary-fixed': '#d5e8cb',
        'tertiary-fixed-dim': '#b9ccb0',
        'on-tertiary-fixed': '#101f0d',
        'on-tertiary-fixed-variant': '#3b4b36',
        outline: '#727973',
        'outline-variant': '#c2c8c1',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        text: '#1b1c1c',
        'text-muted': '#424843',
        'bg-warm': '#fcf9f8',
        sand: '#e8e2d6',
        sage: '#45614e',
        terracotta: '#5d7a66',
        'text-dark': '#1b1c1c',
        emergency: '#ba1a1a',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['Outfit', 'Inter', 'ui-sans-serif', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '600', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600', letterSpacing: '-0.01em' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.125rem',
        '2xl': '1.5rem',
        '3xl': '1.75rem',
        '4xl': '2rem',
        btn: '16px',
        input: '16px',
        card: '24px',
        large: '32px',
        modal: '32px',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        gutter: '24px',
        'section-gap': '80px',
        'section-mobile': '48px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        'container-max': '1240px',
      },
      maxWidth: {
        content: '1240px',
      },
      boxShadow: {
        ambient: '0 10px 30px rgba(69, 97, 78, 0.08)',
        card: '0 8px 24px rgba(69, 97, 78, 0.1)',
        lift: '0 14px 36px rgba(69, 97, 78, 0.12)',
        glow: '0 8px 28px rgba(69, 97, 78, 0.18)',
        'glow-red': '0 8px 28px rgba(186, 26, 26, 0.15)',
      },
      keyframes: {
        'fade-scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.97) translateY(8px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        'slide-in-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        'dot-pulse': {
          '0%, 80%, 100%': { opacity: '0.3', transform: 'scale(0.8)' },
          '40%': { opacity: '1', transform: 'scale(1)' },
        },
        'orb-breathe': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.9' },
          '50%': { transform: 'scale(1.08)', opacity: '1' },
        },
        'msg-in': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-scale-in': 'fade-scale-in 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        'slide-in-up': 'slide-in-up 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
        shimmer: 'shimmer 1.5s linear infinite',
        'dot-pulse': 'dot-pulse 1.4s ease-in-out infinite',
        'orb-breathe': 'orb-breathe 4s ease-in-out infinite',
        'msg-in': 'msg-in 0.35s cubic-bezier(0.4, 0, 0.2, 1) forwards',
      },
      backgroundImage: {
        'gradient-sage': 'linear-gradient(135deg, #45614e 0%, #5d7a66 50%, #afceb7 100%)',
        'gradient-warm': 'linear-gradient(180deg, #fcf9f8 0%, #f6f3f2 100%)',
        'gradient-hero': 'linear-gradient(160deg, #fcf9f8 0%, #f0eded 45%, #e8e2d6 100%)',
      },
      transitionTimingFunction: {
        calm: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
    },
  },
  plugins: [],
};
